### PR TITLE
Feature/swodlr UI 70 - add filtering to my data page and re-generation button

### PR DESCRIPTION
**Pull request by jbyrne6**
### Changes

- add filtering to my data page
- add re-generation button to products that have an ERROR status
- doing filtering on client side with data saved in redux store until it is implemented in [swodlr-api](https://github.com/podaac/swodlr/issues/132)

### CODE REVIEW

**Review by viviant100 — CHANGES_REQUESTED** [review]
MGRS Band Adjust with +1 filter is broken (see screenshot below):
Screenshot 2024-05-15 at 7 54 32 AM
Screenshot 2024-05-15 at 7 54 43 AM

**Comment by viviant100** [comment]
@jbyrne6 couple issues:

- (1) range check for filter:  cps don't have negative values (See screenshot #1)
- (2) cal granules didn't work (screenshot #2 
Screenshot 2024-05-16 at 7 36 15 AM

Screenshot 2024-05-16 at 7 32 13 AM

**Comment by jbyrne6** [comment]
@viviant100 , I just pushed 2 fixes addressing the cycle, pass, scene input validation and allowed the inputing of cal orbit inputs.

**Comment by frankinspace** [comment]
Nice work, looks good!

**Comment by jbyrne6** [comment]
> MGRS Band Adjust with +1 filter is broken (see screenshot below): Screenshot 2024-05-15 at 7 54 32 AM Screenshot 2024-05-15 at 7 54 43 AM

I have fixed these

**Review by jbyrne6 — COMMENTED** [review]
I have fixed the issues

**Review by viviant100 — APPROVED** [review]

**Pull request merged**
