### PR TITLE
Feature/swodlr UI 49 - spatial search

### PR DESCRIPTION
**Pull request by jbyrne6**
### Changes

- add the ability to do spatial search with a polygon
- can edit polygon to do the search again
- search is started on closing of the polygon

### CODE REVIEW

**Review by frankinspace — CHANGES_REQUESTED** [review]
When doing a spatial search it appears a granule is found that does not intersect with my spatial area:

Screenshot 2023-12-13 at 11 45 49 AM

**Review by frankinspace — COMMENTED** [review]
Other less important observations:
- When doing spatial search of a large area that includes granules that are not available the red error message box flashes repeatedly
- The zoom after finishing spatial search is disorienting. Would be better to not alter the map view at all after completing the polygon.

**Comment by jbyrne6** [comment]
> Other less important observations:
> 
> * When doing spatial search of a large area that includes granules that are not available the red error message box flashes repeatedly
> * The zoom after finishing spatial search is disorienting. Would be better to not alter the map view at all after completing the polygon.

- fixed the zoom being disorienting on spatial search completion

**Comment by jbyrne6** [comment]
> When doing a spatial search it appears a granule is found that does not intersect with my spatial area:
> 
> Screenshot 2023-12-13 at 11 45 49 AM

- Made a bug issue with the reason for this error here [https://github.com/podaac/swodlr-ui/issues/69](https://github.com/podaac/swodlr-ui/issues/69)

**Comment by frankinspace** [comment]
Still have the flashing error messages which makes it hard to continue using the app:

https://github.com/podaac/swodlr-ui/assets/89428916/aa9c1e7b-11d3-4a7b-bf4a-2a5a69436ac2

Also, if you are zoomed in already, then you add a shape the map still seems to reset itself:

https://github.com/podaac/swodlr-ui/assets/89428916/1a3bfcb2-51d5-43ce-adfb-e5b157743ee3

**Comment by frankinspace** [comment]
If you want to break the flashing error messages into a distinct bug ticket I'd support that as well

**Review by frankinspace — APPROVED** [review]

**Pull request merged**
