### PR TITLE
Feature/swodlr UI 102 - refactor spatial search validation

### PR DESCRIPTION
**Pull request by jbyrne6**
### Changes

- Refactored the GranulesTable.tsx page so that footprint metadata more efficient.

### CODE REVIEW

**Review by joshgarde — APPROVED** [review]
Looks good to me; is this deployed for testing in SIT?

**Review by joshgarde — CHANGES_REQUESTED** [review]
image
Looks like spacial searches on SIT are unstable and there's still multiple requests occurring for 1 spacial lookup. I'm not sure what the optimization in the PR is if multiple requests are still being launched on a single spacial lookup

**Comment by jbyrne6** [comment]
> image Looks like spacial searches on SIT are unstable and there's still multiple requests occurring for 1 spacial lookup. I'm not sure what the optimization in the PR is if multiple requests are still being launched on a single spacial lookup

I will check this out and see where the extra requests are coming from. The requests should have been reduced to only one to get the footprint polygons for the map.

**Review by joshgarde — COMMENTED** [review]
image
I'm still seeing multiple requests per 1 spacial search. Is this the furthest we can optimize this down to at this point?

**Comment by jbyrne6** [comment]
> image I'm still seeing multiple requests per 1 spacial search. Is this the furthest we can optimize this down to at this point?

Were these calls from the granules saved in the url parameters being added on refresh or from the spatial search? If they are from the url parameters that is intended but if it is from spatial search that is a bug. Since there will not be too many saved in url parameters I decided not to optimize that yet and only optimize spatial search for the sake of time.

**Review by joshgarde — APPROVED** [review]
Rereviewed the SIT implementation. Nice work! LGTM

**Pull request merged**
