### PR TITLE
Implement basic wireframe

### PR DESCRIPTION
**Pull request by jbyrne6**
- table resizing and responsive table
- collapsable footer
- started table resizing feature

### CODE REVIEW

**Review by frankinspace — COMMENTED** [review]
Couple questions @jbyrne6 

- Can you update to use minimum node v18? That's the current LTS release so I think we should start there.
- I tried doing this locally and I had to run `npm audit fix --force` in order to avoid an SSL error when starting the development server
- Once I resolved the SSL error, I still can't start the development server. I get an error `Module not found: Error: Can't resolve 'react-leaflet/lib'`
Should I be able to start this in development mode

**Comment by jbyrne6** [comment]
> Couple questions @jbyrne6
> 
> * Can you update to use minimum node v18? That's the current LTS release so I think we should start there.
> * I tried doing this locally and I had to run `npm audit fix --force` in order to avoid an SSL error when starting the development server (this was using node 18)
> * Once I resolved the SSL error, I still can't start the development server. I get an error `Module not found: Error: Can't resolve 'react-leaflet/lib'`
>   Should I be able to start this in development mode

I upgraded to node 18 and also fixed the react-leaflet/lib error. You should be able to run this with `npm install ` and the `npm start`. Let me know if it is working for you with my changes.

**Comment by frankinspace** [comment]
Works for me now. Nice job

**Review by frankinspace — APPROVED** [review]

**Comment by frankinspace** [comment]
Skipped. Not being merged

**Pull request closed without merging**
